### ISSUE TITLE
Require Emails When Signing Up

### ISSUE THREAD

**Issue by Ezequiel-Valencia** [AvocadoMoon/Music-Recommender#12]
### Problem
Bots can simply create infinite accounts because we don't force creation verification. Also how to contact users?

### Solution
Require email verification. Ensuring that the email used is indeed a valid one.

### Tasks

- [ ] Setup a mail server which is used only for email verification
- [ ] Check if the email is valid according to specifications
- [ ] Check if it's one of the few allowed email addresses (gmail, yahoo, proton, etc...)
- [ ] Finally do the expensive mail server check.

Email Verify Resources (Use net/mail library, plus external library, plus email name filter):
[Library](https://github.com/badoux/checkmail) | [Stack Overflow](https://stackoverflow.com/questions/66624011/how-to-validate-an-email-address-in-golang) | [Reddit](https://www.reddit.com/r/golang/comments/1g7ja07/updates_on_the_email_verifier_project_in_go/)

**Comment by Ezequiel-Valencia** [comment]
Even if emails aren't validated it would still be a required addition since the users who are truthful will have some contact point available.
