### ISSUE TITLE
Story: Database to store the music info

### ISSUE THREAD

**Issue by Ezequiel-Valencia** [AvocadoMoon/Music-Recommender#5]
### Purpose
Table to store all of the information regarding the music.

### Tasks
- [x] Create separate Go structs that clients use to send data

### Tables

- [x] Music to be voted on
- [x] Music already voted on
- [x] Users who can submit
- [x] Double check all types, and whether they should be strings or runes
- [ ] Special Days (Where only one genre of music, "persons" set three, holiday special, etc...)
   -  Limit the # of special days a curator can create
   -  Holiday specials only done by yours truly or high ranking curators
